#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错 

spring: 
    profiles: 
        active: dev # 激活开发环境配置 
--- 
server: 
    port: 4001 #端口号 
spring: 
    profiles: dev # 开发环境 
    application: 
        name: microservice-config-dev 
--- 
server: 
    port: 4002 #端口号 
spring: 
    profiles: prod # 生产环境 
    application: 
        name: microservice-config-prod 
#保存时注意，选择 UTF-8 保存
<<<<<<< HEAD
2342562346346234623626
=======
111111111111111111111111111111
>>>>>>> origin/master
<<<<<<< HEAD
44
=======
13413434214321342341312341234214
>>>>>>> d85b53f5f91a45113a5bf0e02c13e752941540a2
申肖肖啊
撒旦法是藕粉色
<<<<<<< HEAD
111111110101010101
=======
而我二群翁人情味儿无群二翁人 
>>>>>>> refs/remotes/origin/master
<<<<<<< HEAD
呵呵哒
=======
八格牙路
>>>>>>> 58ee981494cc4338e9ca5fd2bfe952d37ac52a41
<<<<<<< HEAD
我也是知道啦。
=======
原来如此啊。
>>>>>>> refs/remotes/origin/master
<<<<<<< HEAD
2
=======
1
>>>>>>> 7204bb37b30158072e3da151bbe079448cd9f358
<<<<<<< HEAD
88888
=======
99999
>>>>>>> dbaffd68dd297f28f624d0941b3ece0c4f51e0a6
<<<<<<< HEAD
0啊啊啊
=======
0
>>>>>>> fa4818a20f8f88881c3b738b709c6b705d4076a3
